server:
  port: 8085
spring:
  application:
    name: user-consumer-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
      prefer-ip-address: true


USER-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule