server:
  port: 8088
spring:
  application:
    name: user-consumer-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
      prefer-ip-address: true