spring:
  application:
    name: apigetway-zuul
server:
  port: 10900
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
zuul:
  routes:
    user-service: /abc/** #映射路由
  ignored-services: user-consumer  #多个服务以逗号分隔。


